In [1]:
import cv2
import tensorflow as tf
from tensorflow import keras
from keras.models import load_model
import numpy as np
from pygame import mixer

ModuleNotFoundError: No module named 'tensorflow.python.trackable'

In [4]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r"C:\Users\S U B H A M\Downloads\Compressed\Driver-Drowsiness-Detection-using-Deep-Learning-main\Driver-Drowsiness-Detection-using-Deep-Learning-main\models\model1.h5")

In [5]:
mixer.init()
sound= mixer.Sound(r"C:\Users\S U B H A M\Downloads\Compressed\Driver-Drowsiness-Detection-using-Deep-Learning-main\Driver-Drowsiness-Detection-using-Deep-Learning-main\alarm.wav")
cap = cv2.VideoCapture(0)
Score = 0
while True:
    ret, frame = cap.read()
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        #cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
       # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        # if eyes are closed
        if prediction[0][0]>0.50:
            cv2.putText(frame,'closed',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>10):
                try:
                    sound.play()
                except:
                    pass
            
        # if eyes are open
        elif prediction[0][1]>0.90:
            cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-1
            if (Score<0):
                Score=0
            
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()


1/1 [==============================] - 3s 3s/step
[[0.92432356 0.07567648]]
1/1 [==============================] - 0s 56ms/step
[[0.6705062  0.32949382]]
1/1 [==============================] - 0s 54ms/step
[[0.6059859 0.3940141]]
1/1 [==============================] - 0s 54ms/step
[[0.398088 0.601912]]
1/1 [==============================] - 0s 54ms/step
[[0.9569264  0.04307361]]
1/1 [==============================] - 0s 55ms/step
[[0.71890146 0.2810986 ]]
1/1 [==============================] - 0s 52ms/step
[[0.46260703 0.5373929 ]]
1/1 [==============================] - 0s 55ms/step
[[0.00562817 0.9943718 ]]
1/1 [==============================] - 0s 56ms/step
[[0.0012811 0.998719 ]]
1/1 [==============================] - 0s 54ms/step
[[0.00160916 0.9983909 ]]
1/1 [==============================] - 0s 55ms/step
[[0.04073493 0.95926505]]
1/1 [==============================] - 0s 54ms/step
[[0.00197791 0.9980221 ]]
1/1 [==============================] - 0s 55ms/step
[[0.45567995 0.5443200

KeyboardInterrupt: 